package git

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mrz1836/go-pre-commit/internal/config"
	prerrors "github.com/mrz1836/go-pre-commit/internal/errors"
)

// hookMarker identifies hook scripts generated by this installer
const hookMarker = "Go Pre-commit Hook"

// hookScript is the git hook script written by the installer. It resolves the
// repository root when it runs rather than embedding the installing checkout's
// path: hooks live in the git directory shared by every worktree, so a fixed
// path would make commits from a linked worktree run checks against another tree.
const hookScript = `#!/bin/bash
# Go Pre-commit Hook
# This hook is managed by Go pre-commit system
# Generated automatically - do not edit manually

# Configuration
# Git runs hooks from the top of the working tree being committed, so resolve
# the root here; this keeps the hook correct for every git worktree.
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [[ -z "$REPO_ROOT" ]]; then
    REPO_ROOT="$(pwd)"
fi
BINARY_NAME="go-pre-commit"
CONFIG_FILE="$REPO_ROOT/.github/.env.base"

# CI Environment Detection
if [[ -n "$CI" || -n "$GITHUB_ACTIONS" || -n "$GITLAB_CI" || -n "$JENKINS_URL" ]]; then
    CI_ENV=true
else
    CI_ENV=false
fi

# Check if pre-commit system is enabled
if [[ -f "$CONFIG_FILE" ]]; then
    # Source config to check if enabled
    if grep -q "^ENABLE_GO_PRE_COMMIT=false" "$CONFIG_FILE" 2>/dev/null; then
        if [[ "$CI_ENV" != "true" ]]; then
            echo "Go pre-commit system is disabled (ENABLE_GO_PRE_COMMIT=false)"
        fi
        exit 0
    fi
fi

# Find the go-pre-commit binary
BINARY_PATH=""

# Search locations in order of preference
SEARCH_PATHS=(
    "$(command -v $BINARY_NAME 2>/dev/null)"  # In PATH
    "$(go env GOPATH 2>/dev/null)/bin/$BINARY_NAME"  # GOPATH/bin
    "./bin/$BINARY_NAME"  # Local bin directory
    "./$BINARY_NAME"  # Root directory
    "./cmd/go-pre-commit/$BINARY_NAME"  # Development location
)

for path in "${SEARCH_PATHS[@]}"; do
    if [[ -n "$path" && -x "$path" ]]; then
        BINARY_PATH="$path"
        break
    fi
done

if [[ -z "$BINARY_PATH" ]]; then
    echo "Error: go-pre-commit binary not found"
    echo "Searched locations:"
    for path in "${SEARCH_PATHS[@]}"; do
        if [[ -n "$path" ]]; then
            echo "  - $path"
        fi
    done
    echo ""
    echo "To fix this issue:"
    echo "  1. Install to PATH: go install ./cmd/go-pre-commit"
    echo "  2. Or build locally: go build -o cmd/go-pre-commit/go-pre-commit ./cmd/go-pre-commit"
    exit 1
fi

# Change to repository root for execution
cd "$REPO_ROOT" || {
    echo "Error: Could not change to repository root: $REPO_ROOT"
    exit 1
}

# Execute the pre-commit system
# Pass through environment variables including SKIP
exec "$BINARY_PATH" run
`

// Installer handles git hook installation
type Installer struct {
	repoRoot     string
	preCommitDir string
	config       *config.Config
	runGit       gitRunner
}

// NewInstaller creates a new hook installer
func NewInstaller(repoRoot, preCommitDir string) *Installer {
	return &Installer{
		repoRoot:     repoRoot,
		preCommitDir: preCommitDir,
		runGit:       execGitRunner,
	}
}

// NewInstallerWithConfig creates a new hook installer with configuration
func NewInstallerWithConfig(repoRoot, preCommitDir string, cfg *config.Config) *Installer {
	return &Installer{
		repoRoot:     repoRoot,
		preCommitDir: preCommitDir,
		config:       cfg,
		runGit:       execGitRunner,
	}
}

// HooksDir returns the directory git runs hooks from for this repository.
// In a linked worktree this is the hooks directory of the shared git
// directory, and core.hooksPath is honored when set.
func (i *Installer) HooksDir() (string, error) {
	return resolveHooksDir(context.Background(), i.runGit, i.repoRoot)
}

// hookPath returns the path of the given hook type in the hooks directory
func (i *Installer) hookPath(hookType string) (string, error) {
	hooksDir, err := i.HooksDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(hooksDir, hookType), nil
}

// InstallHook installs a git hook with enhanced validation and conflict resolution
func (i *Installer) InstallHook(hookType string, force bool) error {
	// Pre-installation validation
	if err := i.validateInstallation(hookType); err != nil {
		return fmt.Errorf("installation validation failed: %w", err)
	}

	hookPath, err := i.hookPath(hookType)
	if err != nil {
		return fmt.Errorf("failed to locate hooks directory: %w", err)
	}

	// Handle existing hooks
	if err := i.handleExistingHook(hookPath, force); err != nil {
		return err
	}

	// Create hooks directory if it doesn't exist
	hooksDir := filepath.Dir(hookPath)
	if err := os.MkdirAll(hooksDir, 0o750); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	// Write hook script
	if err := os.WriteFile(hookPath, []byte(i.GenerateHookScript()), 0o755); err != nil { //nolint:gosec // Hook script must be executable
		return fmt.Errorf("failed to write hook script: %w", err)
	}

	// Post-installation verification
	if err := i.verifyInstallation(hookPath); err != nil {
		return fmt.Errorf("installation verification failed: %w", err)
	}

	return nil
}

// UninstallHook removes a git hook if it was installed by us
func (i *Installer) UninstallHook(hookType string) (bool, error) {
	hookPath, err := i.hookPath(hookType)
	if err != nil {
		return false, fmt.Errorf("failed to locate hooks directory: %w", err)
	}

	// Check if hook exists
	content, err := os.ReadFile(hookPath) //nolint:gosec // Path is validated
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil // Hook doesn't exist
		}
		return false, fmt.Errorf("failed to read hook: %w", err)
	}

	// Check if it's our hook
	if !strings.Contains(string(content), hookMarker) {
		return false, nil // Not our hook
	}

	// Remove the hook
	if err := os.Remove(hookPath); err != nil {
		return false, fmt.Errorf("failed to remove hook: %w", err)
	}

	// Check for and restore backup if it exists
	if err := i.restoreBackupIfExists(hookPath); err != nil {
		// Log warning but don't fail uninstall
		fmt.Fprintf(os.Stderr, "Warning: failed to restore backup hook: %v\n", err)
	}

	return true, nil
}

// IsHookInstalled checks if a hook is installed
func (i *Installer) IsHookInstalled(hookType string) bool {
	hookPath, err := i.hookPath(hookType)
	if err != nil {
		return false
	}

	content, err := os.ReadFile(hookPath) //nolint:gosec // Path is validated
	if err != nil {
		return false
	}

	return strings.Contains(string(content), hookMarker)
}

// validateInstallation performs pre-installation validation
func (i *Installer) validateInstallation(hookType string) error {
	// Validate git repository (a .git directory, or a .git file in a worktree)
	if _, err := i.HooksDir(); err != nil {
		return err
	}

	// Validate hook type
	validHookTypes := map[string]bool{
		"pre-commit":  true,
		"pre-push":    true,
		"commit-msg":  true,
		"post-commit": true,
	}
	if !validHookTypes[hookType] {
		return fmt.Errorf("%w: %s", prerrors.ErrUnsupportedHookType, hookType)
	}

	// Validate pre-commit directory exists
	preCommitPath := i.preCommitDir
	if !filepath.IsAbs(preCommitPath) {
		preCommitPath = filepath.Join(i.repoRoot, i.preCommitDir)
	}
	if _, err := os.Stat(preCommitPath); os.IsNotExist(err) {
		return fmt.Errorf("%w: %s", prerrors.ErrPreCommitDirNotExist, preCommitPath)
	}

	// Validate configuration if available
	if i.config != nil {
		if err := i.config.Validate(); err != nil {
			return fmt.Errorf("configuration validation failed: %w", err)
		}
	}

	return nil
}

// handleExistingHook manages existing hook conflicts
func (i *Installer) handleExistingHook(hookPath string, force bool) error {
	if _, err := os.Stat(hookPath); err == nil {
		// Hook exists, read content
		content, readErr := os.ReadFile(hookPath) //nolint:gosec // Path is validated
		if readErr != nil {
			return fmt.Errorf("failed to read existing hook: %w", readErr)
		}

		// Check if it's our hook
		if strings.Contains(string(content), hookMarker) {
			// It's our hook, update it (this is safe)
			return nil
		}

		// It's not our hook
		if !force {
			return fmt.Errorf("%w: %s (use --force to overwrite)", os.ErrExist, hookPath)
		}

		// Backup existing hook if force is used
		backupPath := hookPath + ".backup." + fmt.Sprintf("%d", os.Getpid())
		if err := os.Rename(hookPath, backupPath); err != nil {
			return fmt.Errorf("failed to backup existing hook: %w", err)
		}
	}

	return nil
}

// GenerateHookScript returns the hook script to install. The script resolves
// the repository root at run time, so it works from any git worktree.
func (i *Installer) GenerateHookScript() string {
	return hookScript
}

// verifyInstallation checks that the installation was successful
func (i *Installer) verifyInstallation(hookPath string) error {
	// Check file exists and is executable
	info, err := os.Stat(hookPath)
	if err != nil {
		return fmt.Errorf("hook file not found after installation: %w", err)
	}

	// Check permissions
	if info.Mode()&0o111 == 0 {
		return fmt.Errorf("%w: %s", prerrors.ErrHookNotExecutable, hookPath)
	}

	// Check content contains our marker
	content, err := os.ReadFile(hookPath) //nolint:gosec // Path is validated
	if err != nil {
		return fmt.Errorf("failed to read installed hook: %w", err)
	}

	if !strings.Contains(string(content), hookMarker) {
		return fmt.Errorf("%w", prerrors.ErrHookMarkerMissing)
	}

	return nil
}

// restoreBackupIfExists restores a backed up hook if one exists
func (i *Installer) restoreBackupIfExists(hookPath string) error {
	// Look for backup files
	dir := filepath.Dir(hookPath)
	base := filepath.Base(hookPath)
	pattern := base + ".backup.*"

	matches, err := filepath.Glob(filepath.Join(dir, pattern))
	if err != nil {
		return fmt.Errorf("failed to search for backup files: %w", err)
	}

	if len(matches) == 0 {
		return nil // No backup to restore
	}

	// Use the most recent backup (last in sorted order)
	backupPath := matches[len(matches)-1]

	// Restore the backup
	if err := os.Rename(backupPath, hookPath); err != nil {
		return fmt.Errorf("failed to restore backup from %s: %w", backupPath, err)
	}

	return nil
}

// GetInstallationStatus returns detailed information about hook installation status
func (i *Installer) GetInstallationStatus(hookType string) (*InstallationStatus, error) {
	status := &InstallationStatus{
		HookType: hookType,
	}

	hookPath, err := i.hookPath(hookType)
	if err != nil {
		return status, fmt.Errorf("failed to locate hooks directory: %w", err)
	}
	status.HookPath = hookPath

	// Check if hook file exists
	info, err := os.Stat(hookPath)
	if os.IsNotExist(err) {
		status.Installed = false
		status.Message = "Hook not installed"
		return status, nil
	}
	if err != nil {
		return status, fmt.Errorf("failed to stat hook file: %w", err)
	}

	status.Executable = info.Mode()&0o111 != 0
	status.FileMode = info.Mode()
	status.ModTime = info.ModTime()

	// Read and analyze content
	content, err := os.ReadFile(hookPath) //nolint:gosec // Path is validated
	if err != nil {
		return status, fmt.Errorf("failed to read hook file: %w", err)
	}

	status.IsOurHook = strings.Contains(string(content), hookMarker)
	if status.IsOurHook {
		status.Installed = true
		status.Outdated = string(content) != i.GenerateHookScript()
		status.Message = "Go pre-commit hook installed and ready"
		if status.Outdated {
			status.Message = "Go pre-commit hook installed but outdated (run 'go-pre-commit install' to update)"
		}
		if !status.Executable {
			status.Message += " (warning: not executable)"
		}
	} else {
		status.Installed = false
		status.Message = "Different hook installed (not Go pre-commit)"
		status.ConflictingHook = true
	}

	return status, nil
}

// InstallationStatus provides detailed information about hook installation
type InstallationStatus struct {
	HookType        string
	HookPath        string
	Installed       bool
	IsOurHook       bool
	Outdated        bool // Our hook, but generated by a different version
	Executable      bool
	ConflictingHook bool
	FileMode        os.FileMode
	ModTime         time.Time
	Message         string
}
