project:
  name: go-pre-commit
  binary: go-pre-commit
  module: github.com/mrz1836/go-pre-commit
  main: ./cmd/go-pre-commit

build:
  # Custom ldflags with version injection
  ldflags:
    - "-s -w"
    - "-X main.injectedVersion={{.Version}}"
    - "-X main.injectedCommit={{.Commit}}"
    - "-X main.injectedBuildDate={{.Date}}"
  flags:
    - "-trimpath"
  output: "./cmd/go-pre-commit/go-pre-commit"
