# Common makefile commands & variables between projects
include .make/common.mk

# Common Golang makefile commands & variables between projects
include .make/go.mk

## Set default repository details if not provided
REPO_NAME  ?= go-pre-commit
REPO_OWNER ?= mrz1836

# Variables
BINARY_NAME := go-pre-commit
BINARY_PATH := ./cmd/$(BINARY_NAME)/$(BINARY_NAME)
GO := go
MODULE := github.com/mrz1836/go-pre-commit

# Build flags with version injection
VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE := $(shell date -u '+%Y-%m-%d_%H:%M:%S_UTC' 2>/dev/null || echo "unknown")

LDFLAGS := -ldflags="-s -w"
BUILD_FLAGS := -trimpath

## build: Build the pre-commit binary
build: generate-version
	@echo "Building $(BINARY_NAME)..."
	@$(GO) build $(BUILD_FLAGS) $(LDFLAGS) -o $(BINARY_PATH) ./cmd/$(BINARY_NAME)
	@echo "Binary built: $(BINARY_PATH)"

## generate-version: Generate version file with build information
generate-version:
	@echo "Generating version information..."
	@echo '// Code generated by build process. DO NOT EDIT.' > ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'package main' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '// getBuildVersion returns the build version' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'func getBuildVersion() string {' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '	return "$(VERSION)"' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '}' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '// getBuildCommit returns the build commit' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'func getBuildCommit() string {' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '	return "$(COMMIT)"' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '}' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '// getBuildBuildDate returns the build date' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'func getBuildBuildDate() string {' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '	return "$(BUILD_DATE)"' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '}' >> ./cmd/$(BINARY_NAME)/version_generated.go

## clean: Clean build artifacts
clean:
	@echo "Cleaning $(BINARY_NAME) artifacts..."
	@rm -f $(BINARY_PATH)
	@$(GO) clean ./...
	@$(MAKE) reset-version
	@echo "Clean complete"

## reset-version: Reset version file to default values for testing
reset-version:
	@echo "Resetting version information to defaults..."
	@echo '// Code generated by build process. DO NOT EDIT.' > ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'package main' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '// getBuildVersion returns the build version' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'func getBuildVersion() string {' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '	return "dev"' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '}' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '// getBuildCommit returns the build commit' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'func getBuildCommit() string {' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '	return "none"' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '}' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '// getBuildBuildDate returns the build date' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo 'func getBuildBuildDate() string {' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '	return "unknown"' >> ./cmd/$(BINARY_NAME)/version_generated.go
	@echo '}' >> ./cmd/$(BINARY_NAME)/version_generated.go

## install: Install the binary to GOPATH/bin
install: build
	@echo "Installing $(BINARY_NAME)..."
	@$(GO) install ./cmd/$(BINARY_NAME)
	@echo "Installed to $$(go env GOPATH)/bin/$(BINARY_NAME)"

### uninstall: Remove the binary from GOPATH/bin
#uninstall:
#	@echo "Uninstalling $(BINARY_NAME)..."
#	@rm -f $$(go env GOPATH)/bin/$(BINARY_NAME)
#	@echo "Uninstalled $(BINARY_NAME)"

# Development helpers
## dev-install: Quick build and install for development
dev-install:
	@$(GO) build -o $(BINARY_PATH) ./cmd/$(BINARY_NAME) && \
		cp $(BINARY_PATH) $$(go env GOPATH)/bin/ && \
		echo "Development build installed"

## dev-test: Run tests for a specific package
dev-test:
	@if [ -z "$(PKG)" ]; then \
		echo "Usage: make dev-test PKG=./internal/config [TEST=TestFunctionName]"; \
	else \
		echo "Running tests for $(PKG)..."; \
		$(GO) test -v $(if $(TEST),-run $(TEST)) $(PKG); \
	fi

## version: Display version information
version:
	@echo "Module: $(MODULE)"
	@echo "Binary: $(BINARY_NAME)"
	@echo "Go version: $$(go version)"
	@echo "Build time: $$(date)"
