// Code generated by build process. DO NOT EDIT.

package main

// getBuildVersion returns the build version
func getBuildVersion() string {
	return "dev"
}

// getBuildCommit returns the build commit
func getBuildCommit() string {
	return "none"
}

// getBuildBuildDate returns the build date
func getBuildBuildDate() string {
	return "unknown"
}
